### ISSUE TITLE
Update JDK 

### ISSUE THREAD

**Issue by Kolla27** [neiman-marcus/terraform-aws-jenkins-ha-agents#3]
Hi,

Please update java-1.8.0-amazon-corretto to java-1.8.0-amazon-corretto-devel to install jdk.

Thanks,
Manoj

**Comment by claydanford** [comment]
Please feel free to fork, make changes, and submit a pull request. Once submitted I will test and approve.

**Comment by claydanford** [comment]
Please feel free to submit a pull request. Once submitted I will test and approve.
