### ISSUE TITLE
Add variables to agen instance types and master instance type separately 

### ISSUE THREAD

**Issue by ChalakaNuwan** [neiman-marcus/terraform-aws-jenkins-ha-agents#56]
Hi 
Can we separate the master instance type and agent instance types since if there is a requirement to use huge size slaves . then no point to create same instance type for master 

ex
["t3.2xlarge", "t3a.2xlarge", "t2.large", "a1.2xlarge"] 
if we need to use 2x large for slaves then this current config will create a 2x large for master as well

**Comment by claydanford** [comment]
Hi @ChalakaNuwan, Yes that would be a welcome addition! Feel free to open a PR, otherwise I will get to it when available.

**Comment by claydanford** [comment]
Closing due to lack of response.
